import re
from playwright.sync_api import Playwright, sync_playwright, expect
from config import car_numbers, car_type, owner, dealer_id


# 작업 1 : 차량 번호 변수로 찾는 부분
# 작업 2 : 로그인 시 딜러 계정 로그인 케이스
def vehicleVerification(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://tcar.encar.com/?firstFg=Y&WT.hit=index_mobile_1st")
    page.locator("div").filter(has_text="/ 1오늘 다시 보지 않기닫기").nth(2).click()
    with page.expect_popup() as page1_info:
        page.locator("li:nth-child(10) > .TopBanner_link_banner__ntmao").click()
    page1 = page1_info.value
    page1.get_by_test_id("btnAside").click()
    page1.get_by_role("button", name="로그인하면 더욱 편리합니다").click()
    page1.get_by_role("link", name="encar ci").nth(1).click()
    page1.get_by_role("textbox", name="아이디").click()
    page1.get_by_role("textbox", name="아이디").fill(dealer_id)
    page1.get_by_role("textbox", name="아이디").press("Tab")
    page1.get_by_role("button", name="전체삭제").press("Tab")
    page1.get_by_role("textbox", name="비밀번호").fill("1")
    page1.get_by_role("textbox", name="비밀번호").press("Enter")
    page1.get_by_role("button", name="로그인").click()
    with page1.expect_popup() as page2_info:
        page1.goto("https://tcar.encar.com/?firstFg=Y&WT.hit=index_mobile_1st")
    page2 = page2_info.value
    page2.goto("https://tcar.encar.com/?firstFg=Y&WT.hit=index_mobile_1st")
    page2.locator("div").filter(has_text="/ 1오늘 다시 보지 않기닫기").nth(2).click()
    page2.get_by_test_id("btnAside").click()
    page2.get_by_role("link", name="마이페이지").click()
    page2.get_by_role("link", name="판매관리").click()
    page2.goto("https://mnew.encar.com/my/my_index.do?method=my_regcar&produce=N")
    page2.get_by_role("button", name="하루동안 보지 않기").click()소
    page2.get_by_role("link", name="차량 검수 등록").first.click()
    page2.get_by_role("button", name="자세히보기").first.click()
    page2.locator("label").filter(has_text="전면 사진 등록").click()
    page2.get_by_role("textbox", name="전면 사진 등록").set_input_files("믿고지점코드(운영).png")
    page2.get_by_role("button", name="전면등화장치 사진").click()
    page2.get_by_role("button", name="닫기").click()
    page2.get_by_role("button", name="자세히보기").nth(1).click()
    page2.locator("label").filter(has_text="후면 사진 등록").click()
    page2.get_by_role("textbox", name="후면 사진 등록").set_input_files("믿고지점코드(운영).png")
    page2.get_by_role("button", name="자세히보기").nth(2).click()
    page2.get_by_role("radio", name="1개").check()
    page2.locator("div").filter(has_text=re.compile(r"^차량키통과차량 키 수량1개2개3개사진내용 입력하기$")).get_by_role("button").nth(1).click()
    page2.locator("div").filter(has_text=re.compile(r"^차량키통과차량 키 수량1개2개3개사진내용 입력하기$")).get_by_label("", exact=True).first.set_input_files("믿고지점코드(운영).png")
    page2.locator("div").filter(has_text=re.compile(r"^제조사 매뉴얼있음없음$")).get_by_label("없음").check()
    page2.locator("div").filter(has_text=re.compile(r"^블랙박스있음없음사진내용 입력하기$")).get_by_label("없음").check()
    page2.locator("div").filter(has_text=re.compile(r"^틴팅\(앞 유리\)있음없음통과 여부통과사진내용 입력하기$")).get_by_label("없음").check()
    page2.get_by_role("link", name="실내").click()
    page2.get_by_role("button", name="자세히보기").first.click()
    page2.get_by_role("button", name="자세히보기").nth(1).click()
    page2.get_by_role("button", name="자세히보기").nth(2).click()
    page2.get_by_role("link", name="휠타이어").click()
    page2.get_by_role("button", name="자세히보기").first.click()
    page2.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(1).click()
    page2.get_by_label("", exact=True).first.set_input_files("믿고지점코드(운영).png")
    page2.locator("[id=\"운전석\\ \\(앞\\)_manufacturer\"]").select_option("금호")
    page2.locator("[id=\"운전석\\ \\(앞\\)_productionDate\"]").click()
    page2.locator("[id=\"운전석\\ \\(앞\\)_productionDate\"]").fill("0124")
    page2.locator("[id=\"운전석\\ \\(앞\\)_tread\"]").click()
    page2.locator("[id=\"운전석\\ \\(앞\\)_tread\"]").fill("10")
    page2.get_by_role("button", name="자세히보기").nth(1).click()
    page2.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(1).click()
    page2.get_by_label("", exact=True).first.set_input_files("믿고지점코드(운영).png")
    page2.locator("[id=\"운전석\\ \\(뒤\\)_manufacturer\"]").select_option("금호")
    page2.locator("[id=\"운전석\\ \\(뒤\\)_productionDate\"]").click()
    page2.locator("[id=\"운전석\\ \\(뒤\\)_productionDate\"]").fill("0124")
    page2.locator("[id=\"운전석\\ \\(뒤\\)_manufacturer\"]").select_option("미쉐린")
    page2.locator("[id=\"운전석\\ \\(뒤\\)_tread\"]").click()
    page2.locator("[id=\"운전석\\ \\(뒤\\)_tread\"]").fill("10")
    page2.get_by_role("button", name="자세히보기").nth(2).click()
    page2.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(1).click()
    page2.get_by_label("", exact=True).first.set_input_files("믿고지점코드(운영).png")
    page2.locator("[id=\"동승석\\ \\(뒤\\)_manufacturer\"]").select_option("굿이어")
    page2.locator("[id=\"동승석\\ \\(뒤\\)_productionDate\"]").click()
    page2.locator("[id=\"동승석\\ \\(뒤\\)_productionDate\"]").fill("0124")
    page2.locator("[id=\"동승석\\ \\(뒤\\)_tread\"]").click()
    page2.locator("[id=\"동승석\\ \\(뒤\\)_tread\"]").fill("10")
    page2.get_by_role("button", name="자세히보기").nth(3).click()
    page2.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(1).click()
    page2.get_by_label("", exact=True).first.set_input_files("믿고지점코드(운영).png")
    page2.locator("[id=\"동승석\\ \\(앞\\)_manufacturer\"]").select_option("굿이어")
    page2.locator("[id=\"동승석\\ \\(앞\\)_productionDate\"]").click()
    page2.locator("[id=\"동승석\\ \\(앞\\)_productionDate\"]").fill("0124")
    page2.locator("[id=\"동승석\\ \\(앞\\)_tread\"]").click()
    page2.locator("[id=\"동승석\\ \\(앞\\)_tread\"]").fill("10")
    page2.get_by_role("link", name="외관").click()
    page2.get_by_role("button", name="자세히보기").first.click()
    page2.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(1).click()
    page2.get_by_label("", exact=True).first.set_input_files("믿고지점코드(운영).png")
    page2.get_by_role("button", name="자세히보기").nth(1).click()
    page2.locator("div").filter(has_text=re.compile(r"^운전석 1열 시트\(필수\)통과사진내용 입력하기$")).get_by_role("button").nth(1).click()
    page2.locator("div").filter(has_text=re.compile(r"^운전석 1열 시트\(필수\)통과사진내용 입력하기$")).get_by_label("", exact=True).first.set_input_files("믿고지점코드(운영).png")
    page2.locator("div").filter(has_text=re.compile(r"^운전석 2열 시트\(필수\)통과사진내용 입력하기$")).get_by_role("button").nth(1).click()
    page2.locator("div").filter(has_text=re.compile(r"^운전석 2열 시트\(필수\)통과사진내용 입력하기$")).get_by_label("").nth(1).set_input_files("믿고지점코드(운영).png")
    page2.get_by_role("button", name="자세히보기").nth(2).click()
    page2.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(1).click()
    page2.get_by_label("", exact=True).first.set_input_files("믿고지점코드(운영).png")
    page2.locator("div").filter(has_text=re.compile(r"^리페어장비있음없음$")).get_by_label("없음").check()
    page2.locator("div").filter(has_text=re.compile(r"^소화기있음없음$")).get_by_label("없음").check()
    page2.get_by_role("button", name="자세히보기").nth(3).click()
    page2.get_by_role("button", name="자세히보기").nth(4).click()
    page2.get_by_role("link", name="부가정보").click()
    page2.get_by_role("button", name="자세히보기").nth(2).click()
    page2.get_by_test_id("tarea").click()
    page2.get_by_test_id("tarea").fill("테스트테스트테스트테스트테스테트세트세트세트세트세틋")
    page2.get_by_role("button", name="자세히보기").nth(1).click()
    page2.locator(".BundleImgUpload_box__Vetlj").first.click()
    page2.locator("input").first.set_input_files("믿고지점코드(운영).png")
    page2.locator("div").filter(has_text=re.compile(r"^보증서 사진$")).get_by_role("button").nth(1).click()
    page2.locator("div").filter(has_text=re.compile(r"^보증서 사진$")).get_by_label("").first.set_input_files("믿고지점코드(운영).png")
    page2.get_by_role("button", name="자세히보기").first.click()
    page2.locator("div").filter(has_text=re.compile(r"^자동차 등록증 사진$")).get_by_role("button").nth(1).click()
    page2.locator("div").filter(has_text=re.compile(r"^자동차 등록증 사진$")).get_by_label("").first.set_input_files("믿고지점코드(운영).png")
    page2.locator("div").filter(has_text=re.compile(r"^성능기록부 사진의무성능보험료보험료 가격을 입력해주세요\.원$")).locator("button").first.click()
    page2.locator("div").filter(has_text=re.compile(r"^성능기록부 사진의무성능보험료보험료 가격을 입력해주세요\.원$")).get_by_label("").first.set_input_files("믿고지점코드(운영).png")
    page2.get_by_role("button", name="등록").click()
    page2.get_by_role("button", name="확인").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    vehicleVerification(playwright)
